# Generated by Django 5.2.12 on 2026-03-18 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='code',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='tracker',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='updated_at',
        ),
    ]
