# Generated by Django 5.2.12 on 2026-03-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_issue_code_remove_issue_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='functionality',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
