# Generated by Django 5.2.12 on 2026-03-18 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_issue_functionality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='issue_number',
        ),
    ]
