# Generated by Django 5.2.12 on 2026-03-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_issue_issue_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='functionality',
            field=models.CharField(max_length=255),
        ),
    ]
