# Generated by Django 5.2.12 on 2026-03-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_issue_issue_number_alter_issue_functionality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
