# Generated by Django 5.2.12 on 2026-03-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_issue_issue_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='functionality',
        ),
    ]
