# Generated by Django 5.2.12 on 2026-03-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('core', '0012_remove_issue_functionality'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE "core_issue" RENAME TO "core_issue_old";

            CREATE TABLE "core_issue" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "issue_number" varchar(20) NOT NULL UNIQUE,
                "region_id" bigint NOT NULL REFERENCES "core_region"("id") DEFERRABLE INITIALLY DEFERRED,
                "depot_id" bigint NOT NULL REFERENCES "core_depot"("id") DEFERRABLE INITIALLY DEFERRED,
                "module_id" bigint NOT NULL REFERENCES "core_module"("id") DEFERRABLE INITIALLY DEFERRED,
                "description" text NOT NULL,
                "raised_by_name" varchar(255) NOT NULL,
                "contact_phone" varchar(50) NOT NULL,
                "issue_logged_by_id" integer NOT NULL REFERENCES "auth_user"("id") DEFERRABLE INITIALLY DEFERRED,
                "assigned_to_id" integer NULL REFERENCES "auth_user"("id") DEFERRABLE INITIALLY DEFERRED,
                "severity_id" bigint NOT NULL REFERENCES "core_issueseverity"("id") DEFERRABLE INITIALLY DEFERRED,
                "status_id" bigint NOT NULL REFERENCES "core_issuestatus"("id") DEFERRABLE INITIALLY DEFERRED,
                "date_issue_raised" timestamp with time zone NOT NULL,
                "resolution_notes" text NOT NULL,
                "zetdc_comments" text NOT NULL,
                "longshine_comments" text NOT NULL,
                "resolved_by_id" integer NULL REFERENCES "auth_user"("id") DEFERRABLE INITIALLY DEFERRED,
                "date_issue_resolved" timestamp with time zone NULL,
                "screenshot" varchar(100) NULL
            );

            INSERT INTO "core_issue" (
                "id", "issue_number", "region_id", "depot_id", "module_id", "description", 
                "raised_by_name", "contact_phone", "issue_logged_by_id", "assigned_to_id", 
                "severity_id", "status_id", "date_issue_raised", "resolution_notes", 
                "zetdc_comments", "longshine_comments", "resolved_by_id", 
                "date_issue_resolved", "screenshot"
            )
            SELECT 
                "id", "issue_number", "region_id", "depot_id", "module_id", "description", 
                "raised_by_name", "contact_phone", "issue_logged_by_id", "assigned_to_id", 
                "severity_id", "status_id", "date_issue_raised", "resolution_notes", 
                "zetdc_comments", "longshine_comments", "resolved_by_id", 
                "date_issue_resolved", "screenshot"
            FROM "core_issue_old";

            ALTER TABLE "core_attachment" DROP CONSTRAINT "core_attachment_issue_id_44681ee4_fk_core_issue_id";
            ALTER TABLE "core_attachment" ADD CONSTRAINT "core_attachment_issue_id_44681ee4_fk_core_issue_id" FOREIGN KEY ("issue_id") REFERENCES "core_issue"("id") DEFERRABLE INITIALLY DEFERRED;

            ALTER TABLE "core_issuehistory" DROP CONSTRAINT "core_issuehistory_issue_id_86c26962_fk_core_issue_id";
            ALTER TABLE "core_issuehistory" ADD CONSTRAINT "core_issuehistory_issue_id_86c26962_fk_core_issue_id" FOREIGN KEY ("issue_id") REFERENCES "core_issue"("id") DEFERRABLE INITIALLY DEFERRED;

            DROP TABLE "core_issue_old";
            """
        ),
        migrations.RunSQL(
            sql="""
            CREATE INDEX "core_issue_issue_number_dfd972e7_like" ON "core_issue" ("issue_number" varchar_pattern_ops);
            CREATE INDEX "core_issue_assigned_to_id_145edd50" ON "core_issue" ("assigned_to_id");
            CREATE INDEX "core_issue_depot_id_81393341" ON "core_issue" ("depot_id");
            CREATE INDEX "core_issue_issue_logged_by_id_f5b6acbd" ON "core_issue" ("issue_logged_by_id");
            CREATE INDEX "core_issue_severity_id_efc1079d" ON "core_issue" ("severity_id");
            CREATE INDEX "core_issue_status_id_005a02cf" ON "core_issue" ("status_id");
            CREATE INDEX "core_issue_module_id_cb52aaa6" ON "core_issue" ("module_id");
            CREATE INDEX "core_issue_region_id_bfd99256" ON "core_issue" ("region_id");
            CREATE INDEX "core_issue_resolved_by_id_783982fe" ON "core_issue" ("resolved_by_id");
            """
        ),
    ]
