# Generated by Django 5.2.12 on 2026-03-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_reorder_issue_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='submodule',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='issue',
            name='system',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
