# Generated by Django 5.2.12 on 2026-03-20 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_reorder_issue_columns_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='issue',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='core.module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Submodule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submodules', to='core.module')),
            ],
            options={
                'unique_together': {('module', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='issue',
            name='submodule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='core.submodule'),
        ),
        migrations.AddField(
            model_name='module',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.system'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='core.system'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('system', 'name')},
        ),
    ]
